package common

const PUBLIC_KEY_HEADER = "FPROT!PUB!"
const PRIVATE_KEY_HEADER = "FPROT!PRV!"

const ECDSA_PUBLIC_KEY_HEADER = "FPROT!ECDSAPUB!"
const ECDSA_PRIVATE_KEY_HEADER = "FPROT!ECDSAPRV!"

const SIGNATURE_HEADER = "FPROT!SIG!"
