package common

const PUBLIC_KEY_HEADER = "FPROT-"
const PRIVATE_KEY_HEADER = "FPROT-PRIVATE-KEY-"

const ECDSA_PUBLIC_KEY_HEADER = "FPROT-IDENTITY-"
const ECDSA_PRIVATE_KEY_HEADER = "FPROT-PRIVATE-IDENTITY-"

const SIGNATURE_HEADER = "FPROT!SIG!"
